FROM nginx:1.18.0-alpine
WORKDIR /etc/nginx/templates
COPY default.conf.template /etc/nginx/templates/default.conf.template

# Dockerfile นี้มีการกำหนดให้ใช้ image Nginx เวอร์ชัน 1.18.0
# บน Alpine Linux และคัดลอกไฟล์เทมเพลตการตั้งค่า Nginx ไปยังตำแหน่งที่ระบุในคอนเทนเนอร์